"""
Libellés lisibles des champs de réponse — générés depuis le texte exact des questions
affichées dans medecin.html et patient.html. Utilisé pour l'export Excel.
"""

FIELD_LABELS = {
    "av_s1": "Avant — SUS Q1 : Je voudrais continuer à utiliser ce logiciel fréquemment.",
    "ap_s1": "Après — SUS Q1 : Je voudrais utiliser ce système fréquemment.",
    "av_s2": "Avant — SUS Q2 : Ce logiciel est trop complexe.",
    "ap_s2": "Après — SUS Q2 : Ce système est trop complexe.",
    "av_s3": "Avant — SUS Q3 : Ce logiciel est facile à utiliser.",
    "ap_s3": "Après — SUS Q3 : Ce système est facile à utiliser.",
    "av_s4": "Avant — SUS Q4 : J'aurais besoin du soutien d'un technicien pour être capable d'utiliser ce logiciel correctement.",
    "ap_s4": "Après — SUS Q4 : J'aurais besoin du soutien d'un technicien pour être capable d'utiliser ce système.",
    "av_s5": "Avant — SUS Q5 : Les différentes fonctionnalités de ce logiciel sont bien intégrées.",
    "ap_s5": "Après — SUS Q5 : Les différentes fonctionnalités de ce système sont bien intégrées.",
    "av_s6": "Avant — SUS Q6 : Il y a trop d'incohérences dans ce logiciel.",
    "ap_s6": "Après — SUS Q6 : Il y a trop d'incohérences dans ce système.",
    "av_s7": "Avant — SUS Q7 : La plupart des gens apprendraient à utiliser ce logiciel très rapidement.",
    "ap_s7": "Après — SUS Q7 : La plupart des gens apprendront à utiliser ce système très rapidement.",
    "av_s8": "Avant — SUS Q8 : Ce logiciel est très lourd à utiliser.",
    "ap_s8": "Après — SUS Q8 : Ce système est très lourd à utiliser.",
    "av_s9": "Avant — SUS Q9 : Je me suis senti(e) très à l'aise en utilisant ce logiciel.",
    "ap_s9": "Après — SUS Q9 : Je me suis senti(e) très confiant(e) en utilisant ce système.",
    "av_s10": "Avant — SUS Q10 : J'ai dû apprendre beaucoup de choses avant de pouvoir utiliser ce logiciel efficacement.",
    "ap_s10": "Après — SUS Q10 : J'ai eu besoin d'apprendre beaucoup de choses avant de pouvoir utiliser ce système.",
    "av_n1": "Avant — NASA-TLX Q1 : Quel niveau d'effort mental votre logiciel actuel vous demande-t-il lors d'une consultation préanesthésique ?",
    "ap_n1": "Après — NASA-TLX Q1 : Quel niveau d'effort mental la consultation avec ANALOG vous a-t-elle demandé ?",
    "av_n2": "Avant — NASA-TLX Q2 : Quel niveau d'effort physique (saisie, navigation, clics) votre logiciel actuel vous demande-t-il ?",
    "ap_n2": "Après — NASA-TLX Q2 : Quel niveau d'effort physique l'utilisation d'ANALOG vous a-t-elle demandé ?",
    "av_n3": "Avant — NASA-TLX Q3 : Estimez-vous que votre logiciel actuel vous fait gagner du temps lors de la consultation préanesthésique ?",
    "ap_n3": "Après — NASA-TLX Q3 : Jusqu'à quel point estimez-vous avoir gagné du temps en réalisant une consultation avec ANALOG ?",
    "av_n4": "Avant — NASA-TLX Q4 : Estimez-vous réaliser une consultation d'anesthésie de qualité avec votre logiciel actuel ?",
    "ap_n4": "Après — NASA-TLX Q4 : Jusqu'à quel point estimez-vous avoir réalisé une consultation d'anesthésie de qualité avec ANALOG ?",
    "av_n5": "Avant — NASA-TLX Q5 : Dans quelle mesure votre logiciel actuel génère-t-il chez vous de la frustration, du stress ou de l'agacement ?",
    "ap_n5": "Après — NASA-TLX Q5 : Dans quelle mesure l'utilisation d'ANALOG a-t-elle généré chez vous de la frustration, du stress ou de l'agacement ?",
    "av_c1": "Avant — Bloc 3 Q1 : Mon logiciel actuel assure la qualité globale de ma consultation préanesthésique.",
    "ap_c1": "Après — Bloc 3 Q1 : ANALOG améliore la qualité globale de ma consultation préanesthésique.",
    "av_c2": "Avant — Bloc 3 Q2 : Mon logiciel actuel m'aide à ne pas omettre d'informations cliniques importantes lors de la consultation.",
    "ap_c2": "Après — Bloc 3 Q2 : ANALOG m'aide à ne pas omettre d'informations cliniques importantes lors de la consultation.",
    "av_c3": "Avant — Bloc 3 Q3 : Je fais confiance aux informations restituées par mon logiciel actuel pour étayer mes décisions cliniques.",
    "ap_c3": "Après — Bloc 3 Q3 : Je fais confiance aux informations restituées par ANALOG pour étayer mes décisions cliniques.",
    "av_c4": "Avant — Bloc 3 Q4 : Mon logiciel actuel me permet de réaliser mes consultations rapidement et efficacement.",
    "ap_c4": "Après — Bloc 3 Q4 : L'utilisation d'ANALOG n'a pas introduit de risque supplémentaire pour la prise en charge du patient.",
    "av_c5": "Avant — Bloc 3 Q5 : Mon logiciel actuel améliore ma capacité à recueillir et structurer les informations médicales.",
    "ap_c5": "Après — Bloc 3 Q5 : ANALOG me permet de réaliser mes consultations plus rapidement et plus efficacement.",
    "av_c6": "Avant — Bloc 3 Q6 : L'utilisation de mon logiciel actuel améliore ma performance globale en tant que médecin anesthésiste.",
    "ap_c6": "Après — Bloc 3 Q6 : ANALOG améliore ma capacité à recueillir et structurer les informations médicales.",
    "av_c7": "Avant — Bloc 3 Q7 : La prise en main de mon logiciel actuel a été rapide et intuitive.",
    "ap_c7": "Après — Bloc 3 Q7 : L'utilisation d'ANALOG améliore ma performance globale en tant que médecin anesthésiste.",
    "av_c8": "Avant — Bloc 3 Q8 : L'interface de mon logiciel actuel est claire et lisible pendant la consultation.",
    "ap_c8": "Après — Bloc 3 Q8 : La prise en main d'ANALOG a été rapide et intuitive.",
    "av_c9": "Avant — Bloc 3 Q9 : La navigation et l'accès aux informations dans mon logiciel actuel sont fluides et sans obstacle.",
    "ap_c9": "Après — Bloc 3 Q9 : L'interface d'ANALOG est claire et lisible pendant la consultation.",
    "av_c10": "Avant — Bloc 3 Q10 : Mon logiciel actuel s'intègre naturellement dans mon organisation habituelle de consultation.",
    "ap_c10": "Après — Bloc 3 Q10 : La formation initiale à ANALOG était suffisante pour une utilisation autonome et sécurisée.",
    "av_c11": "Avant — Bloc 3 Q11 : L'utilisation de mon logiciel actuel ne perturbe pas la relation médecin-patient.",
    "ap_c11": "Après — Bloc 3 Q11 : ANALOG s'intègre naturellement dans mon organisation habituelle de consultation.",
    "av_c12": "Avant — Bloc 3 Q12 : Mon logiciel actuel est compatible avec les autres outils informatiques de mon établissement.",
    "ap_c12": "Après — Bloc 3 Q12 : L'utilisation d'ANALOG ne perturbe pas la relation médecin-patient.",
    "av_c13": "Avant — Bloc 3 Q13 : Je considère que mon logiciel actuel garantit la sécurité et la confidentialité des données patients.",
    "ap_c13": "Après — Bloc 3 Q13 : ANALOG est compatible avec les autres outils informatiques de mon établissement.",
    "av_c14": "Avant — Bloc 3 Q14 : Mon logiciel actuel fonctionne de manière fiable et stable dans mon environnement de travail.",
    "ap_c14": "Après — Bloc 3 Q14 : Je considère qu'ANALOG garantit la sécurité et la confidentialité des données patients.",
    "av_c15": "Avant — Bloc 3 Q15 : Mon logiciel actuel fonctionne sans bugs, erreurs ou dysfonctionnements notables.",
    "ap_c15": "Après — Bloc 3 Q15 : ANALOG fonctionne de manière fiable et stable dans mon environnement de travail.",
    "av_c16": "Avant — Bloc 3 Q16 : Je suis globalement satisfait(e) de mon logiciel actuel dans ma pratique quotidienne.",
    "ap_c16": "Après — Bloc 3 Q16 : Je suis globalement satisfait(e) de l'utilisation d'ANALOG dans ma pratique quotidienne.",
    "av_c17": "Avant — Bloc 3 Q17 : Je pense qu'un nouveau logiciel dédié à la consultation préanesthésique améliorerait ma pratique.",
    "ap_c17": "Après — Bloc 3 Q17 : Je prévois de continuer à utiliser ANALOG régulièrement dans ma pratique future.",
    "av_c18": "Avant — Bloc 3 Q18 : Je serais prêt(e) à changer de logiciel si un outil plus adapté à mes besoins était disponible.",
    "ap_c18": "Après — Bloc 3 Q18 : Je recommanderais ANALOG à un(e) collègue anesthésiste.",
    "av_txt_q19": "Avant — Q19 (texte libre) : Quelles sont les principales difficultés que vous rencontrez avec votre logiciel actuel ? (ergonomie, lenteur, accès aux données, navigation, saisie, autre…)",
    "av_txt_q20": "Avant — Q20 (texte libre) : Quelles fonctionnalités vous semblent aujourd'hui manquantes dans votre logiciel actuel ?",
    "av_txt_q21": "Avant — Q21 (texte libre) : Avez-vous d'autres commentaires ou remarques concernant votre outil de consultation actuel ?",
    "ap_inc1": "Après — Q19 (incident) : Avez-vous rencontré un dysfonctionnement ou un comportement inattendu d'ANALOG lors de vos consultations ?",
    "ap_inc2": "Après — Q20 (incident) : L'utilisation d'ANALOG a-t-elle, même indirectement, pu contribuer à une situation à risque pour un patient ?",
    "ap_txt_q21": "Après — Q21 (texte libre) : Si oui à l'une des questions précédentes, décrivez brièvement la situation :",
    "ap_txt_q22": "Après — Q22 (texte libre) : Quelle amélioration ou fonctionnalité manquante souhaiteriez-vous voir dans une prochaine version d'ANALOG ?",
    "p1": "Patient Q1 : Accéder à mon espace patient ANALOG a été simple et rapide.",
    "p2": "Patient Q2 : La navigation dans mon espace patient était claire et intuitive.",
    "p3": "Patient Q3 : Je me suis senti(e) en confiance concernant la sécurité de mes informations personnelles.",
    "p4": "Patient Q4 : Je suis à l'aise avec le fait de transmettre mes informations médicales avant ma consultation.",
    "p5": "Patient Q5 : Les questions posées étaient claires et faciles à comprendre.",
    "p6": "Patient Q6 : La navigation dans le questionnaire était simple et bien organisée.",
    "p7": "Patient Q7 : Je comprends pourquoi ces informations me sont demandées avant ma consultation.",
    "p8": "Patient Q8 : La durée pour remplir ce questionnaire m'a semblé raisonnable.",
    "p9": "Patient Q9 : Remplir ce questionnaire a été simple et sans effort.",
    "p10": "Patient Q10 : Le questionnaire a fonctionné correctement, sans problème technique.",
    "p11": "Patient Q11 : L'espace patient s'affichait correctement sur mon appareil (téléphone, tablette ou ordinateur).",
    "p12": "Patient Q12 : Cette démarche en ligne m'a semblé utile pour préparer ma consultation.",
    "p13": "Patient Q13 : J'ai été globalement satisfait(e) de cette expérience.",
    "p14": "Patient Q14 : Je recommanderais cette démarche à un proche devant passer une consultation d'anesthésie.",
    "txt_q15": "Patient Q15 (texte libre) : Avez-vous rencontré une difficulté ou souhaitez-vous nous faire part d'un commentaire ?",
    "support": "Support utilisé pour remplir le questionnaire",
}

def label(field_name):
    """Retourne le libellé lisible d'un champ, ou le nom brut si inconnu (ex: nouveaux champs ajoutés plus tard)."""
    return FIELD_LABELS.get(field_name, field_name)
